with-expecter: True
disable-version-string: True
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName }}Mock"
dir: "mocks"
outpkg: "mocks"
packages:
    github.com/g-villarinho/link-fizz-api/handlers:
            config:
                all: True
                recursive: True
    github.com/g-villarinho/link-fizz-api/services:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/link-fizz-api/repositories:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/link-fizz-api/pkgs/requestcontext:
        config:
            all: True
            recursive: True