// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandlerMock is an autogenerated mock type for the AuthHandler type
type AuthHandlerMock struct {
	mock.Mock
}

type AuthHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthHandlerMock) EXPECT() *AuthHandlerMock_Expecter {
	return &AuthHandlerMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: w, r
func (_m *AuthHandlerMock) Login(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthHandlerMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthHandlerMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthHandlerMock_Expecter) Login(w interface{}, r interface{}) *AuthHandlerMock_Login_Call {
	return &AuthHandlerMock_Login_Call{Call: _e.mock.On("Login", w, r)}
}

func (_c *AuthHandlerMock_Login_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthHandlerMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthHandlerMock_Login_Call) Return() *AuthHandlerMock_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthHandlerMock_Login_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthHandlerMock_Login_Call {
	_c.Run(run)
	return _c
}

// Logout provides a mock function with given fields: w, r
func (_m *AuthHandlerMock) Logout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthHandlerMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthHandlerMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthHandlerMock_Expecter) Logout(w interface{}, r interface{}) *AuthHandlerMock_Logout_Call {
	return &AuthHandlerMock_Logout_Call{Call: _e.mock.On("Logout", w, r)}
}

func (_c *AuthHandlerMock_Logout_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthHandlerMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthHandlerMock_Logout_Call) Return() *AuthHandlerMock_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthHandlerMock_Logout_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthHandlerMock_Logout_Call {
	_c.Run(run)
	return _c
}

// NewAuthHandlerMock creates a new instance of AuthHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandlerMock {
	mock := &AuthHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
