// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkServiceMock is an autogenerated mock type for the LinkService type
type LinkServiceMock struct {
	mock.Mock
}

type LinkServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkServiceMock) EXPECT() *LinkServiceMock_Expecter {
	return &LinkServiceMock_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function with given fields: ctx, userID, originalURL
func (_m *LinkServiceMock) CreateLink(ctx context.Context, userID string, originalURL string) error {
	ret := _m.Called(ctx, userID, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, originalURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkServiceMock_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type LinkServiceMock_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - originalURL string
func (_e *LinkServiceMock_Expecter) CreateLink(ctx interface{}, userID interface{}, originalURL interface{}) *LinkServiceMock_CreateLink_Call {
	return &LinkServiceMock_CreateLink_Call{Call: _e.mock.On("CreateLink", ctx, userID, originalURL)}
}

func (_c *LinkServiceMock_CreateLink_Call) Run(run func(ctx context.Context, userID string, originalURL string)) *LinkServiceMock_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LinkServiceMock_CreateLink_Call) Return(_a0 error) *LinkServiceMock_CreateLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkServiceMock_CreateLink_Call) RunAndReturn(run func(context.Context, string, string) error) *LinkServiceMock_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURLByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *LinkServiceMock) GetOriginalURLByShortCode(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURLByShortCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkServiceMock_GetOriginalURLByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURLByShortCode'
type LinkServiceMock_GetOriginalURLByShortCode_Call struct {
	*mock.Call
}

// GetOriginalURLByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *LinkServiceMock_Expecter) GetOriginalURLByShortCode(ctx interface{}, shortCode interface{}) *LinkServiceMock_GetOriginalURLByShortCode_Call {
	return &LinkServiceMock_GetOriginalURLByShortCode_Call{Call: _e.mock.On("GetOriginalURLByShortCode", ctx, shortCode)}
}

func (_c *LinkServiceMock_GetOriginalURLByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *LinkServiceMock_GetOriginalURLByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LinkServiceMock_GetOriginalURLByShortCode_Call) Return(_a0 string, _a1 error) *LinkServiceMock_GetOriginalURLByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkServiceMock_GetOriginalURLByShortCode_Call) RunAndReturn(run func(context.Context, string) (string, error)) *LinkServiceMock_GetOriginalURLByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetShortURLs provides a mock function with given fields: ctx
func (_m *LinkServiceMock) GetShortURLs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetShortURLs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkServiceMock_GetShortURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShortURLs'
type LinkServiceMock_GetShortURLs_Call struct {
	*mock.Call
}

// GetShortURLs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkServiceMock_Expecter) GetShortURLs(ctx interface{}) *LinkServiceMock_GetShortURLs_Call {
	return &LinkServiceMock_GetShortURLs_Call{Call: _e.mock.On("GetShortURLs", ctx)}
}

func (_c *LinkServiceMock_GetShortURLs_Call) Run(run func(ctx context.Context)) *LinkServiceMock_GetShortURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkServiceMock_GetShortURLs_Call) Return(_a0 []string, _a1 error) *LinkServiceMock_GetShortURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkServiceMock_GetShortURLs_Call) RunAndReturn(run func(context.Context) ([]string, error)) *LinkServiceMock_GetShortURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkServiceMock creates a new instance of LinkServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkServiceMock {
	mock := &LinkServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
