// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/g-villarinho/link-fizz-api/models"
	mock "github.com/stretchr/testify/mock"
)

// LinkVisitRepositoryMock is an autogenerated mock type for the LinkVisitRepository type
type LinkVisitRepositoryMock struct {
	mock.Mock
}

type LinkVisitRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkVisitRepositoryMock) EXPECT() *LinkVisitRepositoryMock_Expecter {
	return &LinkVisitRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateLinkVisit provides a mock function with given fields: ctx, linkVisit
func (_m *LinkVisitRepositoryMock) CreateLinkVisit(ctx context.Context, linkVisit *models.LinkVisit) error {
	ret := _m.Called(ctx, linkVisit)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinkVisit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LinkVisit) error); ok {
		r0 = rf(ctx, linkVisit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkVisitRepositoryMock_CreateLinkVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinkVisit'
type LinkVisitRepositoryMock_CreateLinkVisit_Call struct {
	*mock.Call
}

// CreateLinkVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - linkVisit *models.LinkVisit
func (_e *LinkVisitRepositoryMock_Expecter) CreateLinkVisit(ctx interface{}, linkVisit interface{}) *LinkVisitRepositoryMock_CreateLinkVisit_Call {
	return &LinkVisitRepositoryMock_CreateLinkVisit_Call{Call: _e.mock.On("CreateLinkVisit", ctx, linkVisit)}
}

func (_c *LinkVisitRepositoryMock_CreateLinkVisit_Call) Run(run func(ctx context.Context, linkVisit *models.LinkVisit)) *LinkVisitRepositoryMock_CreateLinkVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LinkVisit))
	})
	return _c
}

func (_c *LinkVisitRepositoryMock_CreateLinkVisit_Call) Return(_a0 error) *LinkVisitRepositoryMock_CreateLinkVisit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkVisitRepositoryMock_CreateLinkVisit_Call) RunAndReturn(run func(context.Context, *models.LinkVisit) error) *LinkVisitRepositoryMock_CreateLinkVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkVisitRepositoryMock creates a new instance of LinkVisitRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkVisitRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkVisitRepositoryMock {
	mock := &LinkVisitRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
