// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkVisitServiceMock is an autogenerated mock type for the LinkVisitService type
type LinkVisitServiceMock struct {
	mock.Mock
}

type LinkVisitServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkVisitServiceMock) EXPECT() *LinkVisitServiceMock_Expecter {
	return &LinkVisitServiceMock_Expecter{mock: &_m.Mock}
}

// CreateLinkVisit provides a mock function with given fields: ctx, linkID, ipAddress, userAgent
func (_m *LinkVisitServiceMock) CreateLinkVisit(ctx context.Context, linkID string, ipAddress string, userAgent string) error {
	ret := _m.Called(ctx, linkID, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinkVisit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, linkID, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkVisitServiceMock_CreateLinkVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinkVisit'
type LinkVisitServiceMock_CreateLinkVisit_Call struct {
	*mock.Call
}

// CreateLinkVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID string
//   - ipAddress string
//   - userAgent string
func (_e *LinkVisitServiceMock_Expecter) CreateLinkVisit(ctx interface{}, linkID interface{}, ipAddress interface{}, userAgent interface{}) *LinkVisitServiceMock_CreateLinkVisit_Call {
	return &LinkVisitServiceMock_CreateLinkVisit_Call{Call: _e.mock.On("CreateLinkVisit", ctx, linkID, ipAddress, userAgent)}
}

func (_c *LinkVisitServiceMock_CreateLinkVisit_Call) Run(run func(ctx context.Context, linkID string, ipAddress string, userAgent string)) *LinkVisitServiceMock_CreateLinkVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *LinkVisitServiceMock_CreateLinkVisit_Call) Return(_a0 error) *LinkVisitServiceMock_CreateLinkVisit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkVisitServiceMock_CreateLinkVisit_Call) RunAndReturn(run func(context.Context, string, string, string) error) *LinkVisitServiceMock_CreateLinkVisit_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkVisitServiceMock creates a new instance of LinkVisitServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkVisitServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkVisitServiceMock {
	mock := &LinkVisitServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
