// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/g-villarinho/link-fizz-api/models"
	mock "github.com/stretchr/testify/mock"
)

// LoginServiceMock is an autogenerated mock type for the LoginService type
type LoginServiceMock struct {
	mock.Mock
}

type LoginServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginServiceMock) EXPECT() *LoginServiceMock_Expecter {
	return &LoginServiceMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *LoginServiceMock) Login(ctx context.Context, email string, password string) (*models.LoginResponse, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.LoginResponse, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.LoginResponse); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type LoginServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *LoginServiceMock_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *LoginServiceMock_Login_Call {
	return &LoginServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *LoginServiceMock_Login_Call) Run(run func(ctx context.Context, email string, password string)) *LoginServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LoginServiceMock_Login_Call) Return(_a0 *models.LoginResponse, _a1 error) *LoginServiceMock_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoginServiceMock_Login_Call) RunAndReturn(run func(context.Context, string, string) (*models.LoginResponse, error)) *LoginServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginServiceMock creates a new instance of LoginServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginServiceMock {
	mock := &LoginServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
