// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// LoginHandlerMock is an autogenerated mock type for the LoginHandler type
type LoginHandlerMock struct {
	mock.Mock
}

type LoginHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginHandlerMock) EXPECT() *LoginHandlerMock_Expecter {
	return &LoginHandlerMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: w, r
func (_m *LoginHandlerMock) Login(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// LoginHandlerMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type LoginHandlerMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *LoginHandlerMock_Expecter) Login(w interface{}, r interface{}) *LoginHandlerMock_Login_Call {
	return &LoginHandlerMock_Login_Call{Call: _e.mock.On("Login", w, r)}
}

func (_c *LoginHandlerMock_Login_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *LoginHandlerMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *LoginHandlerMock_Login_Call) Return() *LoginHandlerMock_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoginHandlerMock_Login_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *LoginHandlerMock_Login_Call {
	_c.Run(run)
	return _c
}

// NewLoginHandlerMock creates a new instance of LoginHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginHandlerMock {
	mock := &LoginHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
