// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UserHandlerMock is an autogenerated mock type for the UserHandler type
type UserHandlerMock struct {
	mock.Mock
}

type UserHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserHandlerMock) EXPECT() *UserHandlerMock_Expecter {
	return &UserHandlerMock_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: w, r
func (_m *UserHandlerMock) CreateUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UserHandlerMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserHandlerMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *UserHandlerMock_Expecter) CreateUser(w interface{}, r interface{}) *UserHandlerMock_CreateUser_Call {
	return &UserHandlerMock_CreateUser_Call{Call: _e.mock.On("CreateUser", w, r)}
}

func (_c *UserHandlerMock_CreateUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *UserHandlerMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *UserHandlerMock_CreateUser_Call) Return() *UserHandlerMock_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserHandlerMock_CreateUser_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *UserHandlerMock_CreateUser_Call {
	_c.Run(run)
	return _c
}

// GetProfile provides a mock function with given fields: w, r
func (_m *UserHandlerMock) GetProfile(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UserHandlerMock_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserHandlerMock_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *UserHandlerMock_Expecter) GetProfile(w interface{}, r interface{}) *UserHandlerMock_GetProfile_Call {
	return &UserHandlerMock_GetProfile_Call{Call: _e.mock.On("GetProfile", w, r)}
}

func (_c *UserHandlerMock_GetProfile_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *UserHandlerMock_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *UserHandlerMock_GetProfile_Call) Return() *UserHandlerMock_GetProfile_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserHandlerMock_GetProfile_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *UserHandlerMock_GetProfile_Call {
	_c.Run(run)
	return _c
}

// NewUserHandlerMock creates a new instance of UserHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHandlerMock {
	mock := &UserHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
