// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UtilsServiceMock is an autogenerated mock type for the UtilsService type
type UtilsServiceMock struct {
	mock.Mock
}

type UtilsServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UtilsServiceMock) EXPECT() *UtilsServiceMock_Expecter {
	return &UtilsServiceMock_Expecter{mock: &_m.Mock}
}

// GenerateShortCode provides a mock function with given fields: length
func (_m *UtilsServiceMock) GenerateShortCode(length int) (string, error) {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateShortCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(length)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(length)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UtilsServiceMock_GenerateShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateShortCode'
type UtilsServiceMock_GenerateShortCode_Call struct {
	*mock.Call
}

// GenerateShortCode is a helper method to define mock.On call
//   - length int
func (_e *UtilsServiceMock_Expecter) GenerateShortCode(length interface{}) *UtilsServiceMock_GenerateShortCode_Call {
	return &UtilsServiceMock_GenerateShortCode_Call{Call: _e.mock.On("GenerateShortCode", length)}
}

func (_c *UtilsServiceMock_GenerateShortCode_Call) Run(run func(length int)) *UtilsServiceMock_GenerateShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *UtilsServiceMock_GenerateShortCode_Call) Return(_a0 string, _a1 error) *UtilsServiceMock_GenerateShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UtilsServiceMock_GenerateShortCode_Call) RunAndReturn(run func(int) (string, error)) *UtilsServiceMock_GenerateShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewUtilsServiceMock creates a new instance of UtilsServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUtilsServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UtilsServiceMock {
	mock := &UtilsServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
